# Jekyll configuration for GitHub Pages
title: Lev Kozhokaru
description: >-
  Software Engineer specializing in AI-driven systems, test automation, 
  and full-stack development with a focus on quality and innovation.
baseurl: ""
url: "https://kozhokaru.github.io"
github_username: kozhokaru
linkedin_username: levkoz

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lev Kozhokaru"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Kramdown options
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# SEO
author:
  name: Lev Kozhokaru

social:
  name: Lev Kozhokaru
  links:
    - https://github.com/kozhokaru
    - https://linkedin.com/in/levkoz

# Timezone
timezone: America/New_York